#!/bin/bash

DIST=`cat /var/lib/epgsources/xmltvse2xmltv`
args=("$@")
for ((i=0; i < $#; i++))
{
	if [ "$i" -eq "0" ]; then
		echo -n ""
		#echo "Days: $1"
	elif [ "$i" -eq "1" ]; then
		echo -n ""
		#echo "Pin: $2"
	elif [ "$i" -eq "2" ]; then
		echo -n ""
		#echo "???: $3"
	else
		#echo "Channels ${args[$i]}"
		CHANNEL2="${args[$i]}"
		CHANNEL1=`echo "$DIST" | grep "${CHANNEL2}" | sed -r "s/^[^;]*;//"`
		for j in `seq 0 $1`; do
			DATE=`date --date="$j days" +%Y-%m-%d`
			URL=http://xmltv.xmltv.se/${CHANNEL1}_${DATE}.xml.gz
			#echo $URL
			PAGE=`curl "$URL" 2>/dev/null | gunzip | sed -r "s/${CHANNEL1}/${CHANNEL2}/"`
			if [ "$i" -eq "3" -a "$j" -eq "0" ]; then
				HEADER1=`echo "${PAGE}" | grep -Pzo '<\?xml[^<>]*>'`
				HEADER2=`echo "${PAGE}" | grep -Pzo '<tv[^<>]*>'`
				FOOTER="</tv>"
				echo "$HEADER1"
				echo "$HEADER2"
				echo "<channel id=\"${CHANNEL2}\"><display-name>${CHANNEL2}</display-name><url>http://${CHANNEL2}</url></channel>"
			fi
			PAGE=`echo "${PAGE}" | tail -n +2 | sed -r "N;/\n/s/<!DOCTYPE[^<>]*>//" | sed -r "N;/\n/s/<tv[^<>]*>//" | sed -r "s/<\/tv[^<>]*>//"`
			echo "${PAGE}"
		done
	fi
}

echo "$FOOTER"

exit 0

